#!/bin/bash

# Script parameters
original_dir=$(pwd)
repo_root=$(git rev-parse --show-toplevel)
app_dir="$repo_root/app"

setup() {
}

cleanup_and_exit() {
    # Navigate back to the original directory
    cd "$original_dir" || exit 1

    # Exit with the provided status code after printing the provided message
    if [ $1 -eq 0 ]; then
        echo -e "\033[1;32m$2\033[0m" # Print the message in bold green
    else
        echo -e "\033[1;31m$2\033[0m" # Print the message in bold red
    fi
    exit $1
}

run_tests() {
    # Navigate to the root of the Flutter app
    cd "$app_dir" || cleanup_and_exit 1 "Failed to navigate to $app_dir"

    # Check that the project builds correctly
    flutter build web --wasm || exit 1
}

setup
run_tests || cleanup_and_exit 1 "Pre-push tests failed. Commit aborted."
cleanup_and_exit 0 "Pre-push tests passed. Pushing commits."
