#!/bin/bash

# Script parameters
original_dir=$(pwd)
stash_message="pre-commit $(date +%c)"
repo_root=$(git rev-parse --show-toplevel)
app_dir="$repo_root/app"

setup() {
    # Create a temporary stash to store the unstaged changes
    git stash push --keep-index --include-untracked --quiet --message "$stash_message" \
        || exit 1

    # Navigate to the root of the Flutter app
    cd "$app_dir" || exit 1
}

cleanup_and_exit() {
    # Navigate back to the original directory
    cd "$original_dir" || exit 1

    # Remove the temporary stash if it exists
    last_stash=$(git stash list | head -n 1)
    if [[ $last_stash == *"$stash_message"* ]]; then
      git stash pop --quiet || exit 1
    fi

    # Exit with the provided status code after printing the provided message
    if [ $1 -eq 0 ]; then
        echo -e "\033[1;32m$2\033[0m" # Print the message in bold green
    else
        echo -e "\033[1;31m$2\033[0m" # Print the message in bold red
    fi
    exit $1
}

run_tests() {
    # Check that the project compiles correctly
    flutter analyze || exit 1

    # Check that all flutter tests pass
    flutter test || exit 1
}

setup || cleanup_and_exit 1 "Failed to setup pre-commit hook."
run_tests || cleanup_and_exit 1 "Pre-commit tests failed. Commit aborted."
cleanup_and_exit 0 "Pre-commit tests passed. Proceeding with commit."
