targets:
  $default:
    builders:
      auto_route_generator:auto_route_generator: # this for @RoutePage
        generate_for:
          - lib/pages/*.dart
      auto_route_generator:auto_router_generator: # this for @AutoRouterConfig
        generate_for:
          - lib/router.dart
      riverpod_generator:riverpod_generator:
        generate_for:
          - lib/controllers/*.dart
          - lib/repositories/*.dart
          - lib/services/*.dart
