# This workflow orchestrates the deployment of a Flutter web application to multiple
# environments of Cloudflare Pages. The goal is to test the application with different
# build configurations to choose the best one for the production deployment.
name: Deploy Flutter web app to multiple deployment environments in Cloudflare Pages

on: [push, workflow_dispatch]

jobs:
  Wasm:
    uses: ./.github/workflows/deploy_flutter_web_to_cloudflare.yml
    with:
      buildFlags: '--release --no-web-resources-cdn --wasm'
      deploymentEnvironment: ${{ github.ref_name || 'main' }} # Branch name
      appRoot: 'app'
    secrets: inherit

  HTML-Renderer:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy_flutter_web_to_cloudflare.yml
    with:
      buildFlags: '--release --no-web-resources-cdn --web-renderer html'
      deploymentEnvironment: html_renderer
      appRoot: 'app'
    secrets: inherit
